import fs from 'fs';
import path from 'path';

import * as templates from './templates';

const BACKEND_MANIFESTS_DIR = path.join(__dirname, '../../../backend/docs/manifests');
const FRONTEND_MODULES_DIR = path.join(__dirname, '../../src/modules');
const FRONTEND_APP_DIR = path.join(__dirname, '../../src/app');

export interface Field {
  name: string;
  prismaType: string;
  tsType: string;
  optional: boolean;
  isList: boolean;
  isRelation: boolean;
  isForeignKey: boolean;
  hasDefault: boolean;
  autoGenerated: boolean;
  relatedModel?: string;
}

export interface Endpoint {
  method: string;
  path: string;
  auth: any;
  requestQuery?: Record<string, any>;
  requestParams?: Record<string, string>;
  requestBody?: Record<string, { zod: string; required: boolean }>;
  response: {
    status: number;
    shape?: string;
  };
}

export interface QueryConfig {
  sortableFields: string[];
  filterableFields: string[];
  searchableFields: string[];
}

export interface Manifest {
  moduleName: string;
  modelName: string;
  basePath: string;
  fields: Field[];
  relations: any[];
  queryConfig: QueryConfig;
  endpoints: Endpoint[];
}

function ensureDirectoryExists(dir: string) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

async function main() {
  console.log('Starting frontend generator...');

  if (!fs.existsSync(BACKEND_MANIFESTS_DIR)) {
    console.error(`Manifests directory not found at ${BACKEND_MANIFESTS_DIR}`);
    return;
  }

  const manifestFiles = fs.readdirSync(BACKEND_MANIFESTS_DIR).filter(f => f.endsWith('.manifest.json'));

  for (const file of manifestFiles) {
    const manifestPath = path.join(BACKEND_MANIFESTS_DIR, file);
    const manifestContent = fs.readFileSync(manifestPath, 'utf8');
    const manifest: Manifest = JSON.parse(manifestContent);

    if (!manifest.moduleName) {
      console.warn(`Skipping ${file} - no moduleName found.`);
      continue;
    }

    const moduleDir = path.join(FRONTEND_MODULES_DIR, manifest.moduleName);
    
    // Check if module already exists
    if (fs.existsSync(moduleDir)) {
      console.log(`Module ${manifest.moduleName} already exists, skipping...`);
      continue;
    }

    console.log(`Generating frontend module for: ${manifest.moduleName}`);
    
    // Generate module files
    const typesDir = path.join(moduleDir, 'types');
    const servicesDir = path.join(moduleDir, 'services');
    const actionsDir = path.join(moduleDir, 'actions');
    const componentsDir = path.join(moduleDir, 'components');
    const testsFactoriesDir = path.join(moduleDir, 'tests', 'factories');
    const testsServicesDir = path.join(moduleDir, 'tests', 'services');
    const testsActionsDir = path.join(moduleDir, 'tests', 'actions');

    [typesDir, servicesDir, actionsDir, componentsDir, testsFactoriesDir, testsServicesDir, testsActionsDir].forEach(ensureDirectoryExists);

    fs.writeFileSync(path.join(typesDir, `${manifest.moduleName}.types.ts`), templates.generateTypesTemplate(manifest));
    fs.writeFileSync(path.join(typesDir, `${manifest.moduleName}.zod.ts`), templates.generateZodTemplate(manifest));
    fs.writeFileSync(path.join(servicesDir, `${manifest.moduleName}.api.ts`), templates.generateApiTemplate(manifest));
    fs.writeFileSync(path.join(servicesDir, `${manifest.moduleName}.service.ts`), templates.generateServiceTemplate(manifest));
    fs.writeFileSync(path.join(actionsDir, `${manifest.moduleName}.actions.ts`), templates.generateActionsTemplate(manifest));
    fs.writeFileSync(path.join(componentsDir, `${manifest.modelName}Form.tsx`), templates.generateFormTemplate(manifest));
    fs.writeFileSync(path.join(componentsDir, `${manifest.modelName}Table.tsx`), templates.generateTableTemplate(manifest));
    fs.writeFileSync(path.join(moduleDir, 'index.ts'), templates.generateIndexTemplate(manifest));

    // Generate test files
    fs.writeFileSync(path.join(testsFactoriesDir, `${manifest.moduleName}.factory.ts`), templates.generateFactoryTemplate(manifest));
    fs.writeFileSync(path.join(testsServicesDir, `${manifest.moduleName}.service.test.ts`), templates.generateServiceTestTemplate(manifest));
    fs.writeFileSync(path.join(testsActionsDir, `${manifest.moduleName}.actions.test.ts`), templates.generateActionsTestTemplate(manifest));

    // Generate App Router files
    const appModuleDir = path.join(FRONTEND_APP_DIR, `(${manifest.moduleName})`, manifest.moduleName);
    const appNewDir = path.join(appModuleDir, 'new');
    const appEditDir = path.join(appModuleDir, '[id]');

    [appModuleDir, appNewDir, appEditDir].forEach(ensureDirectoryExists);

    fs.writeFileSync(path.join(appModuleDir, 'page.tsx'), templates.generateAppListPageTemplate(manifest));
    fs.writeFileSync(path.join(appNewDir, 'page.tsx'), templates.generateAppNewPageTemplate(manifest));
    fs.writeFileSync(path.join(appEditDir, 'page.tsx'), templates.generateAppEditPageTemplate(manifest));

    console.log(`Successfully generated ${manifest.moduleName}`);
  }
  
  console.log('Generator finished.');
}

main().catch(console.error);
