/**
 * generate-manifest.ts
 *
 * Produces a machine-readable JSON manifest per module, combining:
 *   - PrismaSchemaProvider (field types, relations, FKs)
 *   - <model>.query-config.ts (sortable/filterable/searchable fields)
 *   - <model>.schemas.ts (Zod constraints for create/update bodies)
 *   - <model>.routes.ts (which base CRUD routes exist + custom routes + auth)
 *
 * Output:
 *   apps/backend/docs/manifests/<module>.manifest.json
 *   apps/backend/docs/manifests/_index.manifest.json
 *
 * Usage:
 *   npx ts-node scripts/generator_scripts/generate-manifest.ts
 */

import * as fs from "fs";
import * as path from "path";
import {
  Project,
  SyntaxKind,
  Node,
  ObjectLiteralExpression,
  StringLiteral,
} from "ts-morph";
import { PrismaSchemaProvider, ModelInfo, FieldInfo } from "./schema_parser";

// ─── Paths ──────────────────────────────────────────────────────────────────

const PRISMA_SCHEMA_PATH = path.join(__dirname, "../../prisma/schema.prisma");
const MODULES_DIR = path.join(__dirname, "../../src/modules");
const MANIFESTS_DIR = path.join(__dirname, "../../docs/manifests");

// ─── Helpers ────────────────────────────────────────────────────────────────

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function camelCase(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function subdirs(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name);
}

// ─── Manifest types ─────────────────────────────────────────────────────────

interface ManifestField {
  name: string;
  prismaType: string;
  tsType: string;
  optional: boolean;
  isList: boolean;
  isRelation: boolean;
  isForeignKey: boolean;
  relatedModel?: string;
  hasDefault?: boolean;
  autoGenerated: boolean;
}

interface ManifestRelation {
  field: string;
  kind: "one-to-one" | "many-to-one" | "one-to-many" | "many-to-many";
  relatedModule: string;
  relatedModel: string;
  relatedBasePath: string;
}

interface ManifestQueryConfig {
  sortableFields: string[];
  filterableFields: string[];
  searchableFields: string[];
}

interface ManifestBodyField {
  zod: string;
  required: boolean;
}

interface ManifestEndpoint {
  method: string;
  path: string;
  auth: { type: string; role?: string } | null;
  requestParams?: Record<string, string>;
  requestQuery?: Record<string, unknown>;
  requestBody?: Record<string, ManifestBodyField>;
  responseNote?: string;
  response: { status: number; shape?: string };
}

interface ModuleManifest {
  moduleName: string;
  modelName: string;
  basePath: string;
  fields: ManifestField[];
  relations: ManifestRelation[];
  queryConfig: ManifestQueryConfig | null;
  endpoints: ManifestEndpoint[];
}

// ─── Base path extraction (mirrors generate-route-docs.ts) ──────────────────

function extractBasePath(moduleName: string): string {
  const moduleFile = path.join(
    MODULES_DIR,
    moduleName,
    `${moduleName}.module.ts`,
  );
  if (!fs.existsSync(moduleFile)) return `/api/${moduleName}s`;
  const src = fs.readFileSync(moduleFile, "utf8");
  const m = src.match(/prefix\s*:\s*['"]([^'"]+)['"]/);
  return m ? m[1] : `/api/${moduleName}s`;
}

// ─── Query config extraction ─────────────────────────────────────────────────

function extractQueryConfig(moduleName: string): ManifestQueryConfig | null {
  const filePath = path.join(
    MODULES_DIR,
    moduleName,
    `${moduleName}.query-config.ts`,
  );
  if (!fs.existsSync(filePath)) return null;

  const src = fs.readFileSync(filePath, "utf8");

  const extractArray = (varName: string): string[] => {
    const re = new RegExp(`${varName}\\s*:\\s*\\[([^\\]]*)\\]`);
    const m = src.match(re);
    if (!m) return [];
    return m[1]
      .split(",")
      .map((s) => s.trim().replace(/^['"]|['"]$/g, ""))
      .filter(Boolean);
  };

  return {
    sortableFields: extractArray("sortableFields"),
    filterableFields: extractArray("filterableFields"),
    searchableFields: extractArray("searchableFields"),
  };
}

// ─── Zod body-schema extraction (mirrors generate-route-docs.ts logic) ──────

interface RawSchemaField {
  name: string;
  zodExpr: string;
  isOptional: boolean;
}

function extractSchemaFields(
  schemasFilePath: string,
  schemaVarName: string,
): RawSchemaField[] {
  if (!fs.existsSync(schemasFilePath)) return [];

  const src = fs.readFileSync(schemasFilePath, "utf8");
  const varStart = src.indexOf(`export const ${schemaVarName}`);
  if (varStart === -1) return [];

  const bodyObjStart = src.indexOf("body: z.object({", varStart);
  if (bodyObjStart === -1) return [];

  let depth = 0;
  let i = src.indexOf("{", bodyObjStart + "body: z.object(".length);
  const start = i;
  while (i < src.length) {
    if (src[i] === "{") depth++;
    else if (src[i] === "}") {
      depth--;
      if (depth === 0) break;
    }
    i++;
  }
  const bodyContent = src.slice(start + 1, i);

  const fields: RawSchemaField[] = [];
  for (const line of bodyContent.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("//") || trimmed.startsWith("*"))
      continue;
    const fieldMatch = trimmed.match(/^([A-Za-z0-9_]+)\s*:\s*(.+?),?\s*$/);
    if (!fieldMatch) continue;
    const name = fieldMatch[1];
    const zodExpr = fieldMatch[2].trim().replace(/,$/, "");
    const isOptional = zodExpr.includes(".optional()");
    fields.push({ name, zodExpr, isOptional });
  }

  return fields;
}

function toBodyFieldMap(
  fields: RawSchemaField[],
): Record<string, ManifestBodyField> {
  const map: Record<string, ManifestBodyField> = {};
  for (const f of fields) {
    map[f.name] = { zod: f.zodExpr, required: !f.isOptional };
  }
  return map;
}

function schemaHasRefine(
  schemasFilePath: string,
  schemaVarName: string,
): boolean {
  if (!fs.existsSync(schemasFilePath)) return false;
  const src = fs.readFileSync(schemasFilePath, "utf8");
  const varStart = src.indexOf(`export const ${schemaVarName}`);
  if (varStart === -1) return false;
  const nextExport = src.indexOf("export const", varStart + 1);
  const slice =
    nextExport === -1 ? src.slice(varStart) : src.slice(varStart, nextExport);
  return slice.includes(".refine(");
}

// ─── Routes analysis (mirrors generate-route-docs.ts) ───────────────────────

type BaseSchemaKey = "get" | "create" | "update" | "delete";

function isBaseRouterProtected(
  project: Project,
  routesFilePath: string,
): boolean {
  let isProtected = false;
  const sf =
    project.getSourceFile(routesFilePath) ??
    project.addSourceFileAtPath(routesFilePath);

  sf.getDescendantsOfKind(SyntaxKind.CallExpression).forEach((call) => {
    const expr = call.getExpression();
    if (!Node.isPropertyAccessExpression(expr)) return;

    const obj = expr.getExpression().getText();
    const method = expr.getName();

    if (obj === "finalRouter" && method === "use") {
      const argsText = call.getArguments().map((a) => a.getText()).join(", ");
      if (
        argsText.includes("authMiddleware") ||
        argsText.includes("AuthMiddleware")
      ) {
        isProtected = true;
      }
    }
  });

  return isProtected;
}

function extractBaseRouterSchemaKeys(
  project: Project,
  routesFilePath: string,
): Set<BaseSchemaKey> {
  const keys = new Set<BaseSchemaKey>();
  const sf = project.addSourceFileAtPath(routesFilePath);

  sf.getDescendantsOfKind(SyntaxKind.CallExpression).forEach((call) => {
    const expr = call.getExpression();
    if (!Node.isIdentifier(expr) || expr.getText() !== "createBaseRouter")
      return;

    const args = call.getArguments();
    if (args.length < 2) return;

    const schemasArg = args[1];
    if (!Node.isObjectLiteralExpression(schemasArg)) return;

    (schemasArg as ObjectLiteralExpression).getProperties().forEach((prop) => {
      if (Node.isPropertyAssignment(prop)) {
        const key = prop.getName() as BaseSchemaKey;
        if (["get", "create", "update", "delete"].includes(key)) {
          keys.add(key);
        }
      }
    });
  });

  return keys;
}

interface CustomRoute {
  method: string;
  path: string;
  handlerName: string;
  isProtected: boolean;
  requiredRole?: string;
}

function extractCustomRoutes(
  project: Project,
  routesFilePath: string,
): CustomRoute[] {
  const custom: CustomRoute[] = [];
  const HTTP_METHODS = ["get", "post", "put", "patch", "delete"];

  const sf =
    project.getSourceFile(routesFilePath) ??
    project.addSourceFileAtPath(routesFilePath);

  sf.getDescendantsOfKind(SyntaxKind.CallExpression).forEach((call) => {
    const expr = call.getExpression();
    if (!Node.isPropertyAccessExpression(expr)) return;

    const obj = expr.getExpression().getText();
    const method = expr.getName();

    if (obj !== "finalRouter" || !HTTP_METHODS.includes(method)) return;

    const args = call.getArguments();
    if (args.length < 2) return;

    const firstArg = args[0];
    if (!Node.isStringLiteral(firstArg)) return;

    const routePath = (firstArg as StringLiteral).getLiteralValue();

    let handlerName = "unknown";
    for (let i = args.length - 1; i >= 1; i--) {
      const arg = args[i];
      if (Node.isPropertyAccessExpression(arg)) {
        handlerName = arg.getName();
        break;
      }
      if (Node.isIdentifier(arg)) {
        handlerName = arg.getText();
        break;
      }
    }

    // Detect auth/rbac middleware presence in the argument list
    const argsText = args.map((a) => a.getText()).join(", ");
    const isProtected =
      argsText.includes("authMiddleware") ||
      argsText.includes("AuthMiddleware");
    const roleMatch = argsText.match(/rbacMiddleware\(\s*['"]([^'"]+)['"]/);

    custom.push({
      method: method.toUpperCase(),
      path: routePath,
      handlerName,
      isProtected,
      requiredRole: roleMatch ? roleMatch[1] : undefined,
    });
  });

  return custom;
}

// ─── Relation kind derivation ────────────────────────────────────────────────

function deriveRelationKind(
  model: ModelInfo,
  field: FieldInfo,
  allModels: ModelInfo[],
): ManifestRelation["kind"] {
  const relatedModel = allModels.find((m) => m.name === field.relatedModel);
  if (!relatedModel) return field.isList ? "one-to-many" : "many-to-one";

  // Does this model have a FK scalar backing this relation?
  const hasOwnFk = model.fields.some(
    (f) => f.isForeignKey && f.relatedModel === field.relatedModel,
  );

  if (field.isList) {
    // Check if related model has a FK pointing back to us (one-to-many "one" side)
    const relatedHasFkToUs = relatedModel.fields.some(
      (f) => f.isForeignKey && f.relatedModel === model.name,
    );
    return relatedHasFkToUs ? "one-to-many" : "many-to-many";
  }

  if (hasOwnFk) {
    // Check if this FK is unique (one-to-one) — Prisma schema text has @unique;
    // schema_parser doesn't capture uniqueness, so default to many-to-one unless
    // the related side also has a single (non-list) relation field back to us.
    const relatedField = relatedModel.fields.find(
      (f) => f.isRelation && f.relatedModel === model.name && !f.isList,
    );
    return relatedField ? "one-to-one" : "many-to-one";
  }

  // Inverse side of a single relation object without owning FK
  return "one-to-one";
}

// ─── Build per-module manifest ───────────────────────────────────────────────

function buildManifest(
  moduleName: string,
  model: ModelInfo,
  allModels: ModelInfo[],
  project: Project,
): ModuleManifest {
  const modelName = model.name;
  const basePath = extractBasePath(moduleName);
  const moduleDir = path.join(MODULES_DIR, moduleName);
  const routesFile = path.join(moduleDir, `${moduleName}.routes.ts`);
  const schemasFile = path.join(moduleDir, `${moduleName}.schemas.ts`);

  const AUTO_FIELDS = new Set(["id", "createdAt", "updatedAt"]);

  // ── Fields ──────────────────────────────────────────────────────────────
  const fields: ManifestField[] = model.fields.map((f) => ({
    name: f.name,
    prismaType: f.type,
    tsType: f.isRelation
      ? `${f.type}${f.isList ? "[]" : ""}`
      : mapPrismaScalarToTs(f.type) + (f.isList ? "[]" : ""),
    optional: f.isOptional || f.isRelation, // relation objects always optional (hydrated only)
    isList: f.isList,
    isRelation: f.isRelation,
    isForeignKey: f.isForeignKey,
    relatedModel: f.relatedModel,
    hasDefault: f.hasDefault,
    autoGenerated: AUTO_FIELDS.has(f.name),
  }));

  // ── Relations ───────────────────────────────────────────────────────────
  const relations: ManifestRelation[] = model.fields
    .filter((f) => f.isRelation && f.relatedModel)
    .map((f) => ({
      field: f.name,
      kind: deriveRelationKind(model, f, allModels),
      relatedModule: camelCase(f.relatedModel!),
      relatedModel: f.relatedModel!,
      relatedBasePath: extractBasePath(camelCase(f.relatedModel!)),
    }));

  // ── Query config ────────────────────────────────────────────────────────
  const queryConfig = extractQueryConfig(moduleName);

  // ── Endpoints ───────────────────────────────────────────────────────────
  const endpoints: ManifestEndpoint[] = [];

  if (moduleName === "health" || !fs.existsSync(routesFile)) {
    return {
      moduleName,
      modelName,
      basePath,
      fields,
      relations,
      queryConfig,
      endpoints,
    };
  }

  const schemaKeys = extractBaseRouterSchemaKeys(project, routesFile);
  const customRoutes = extractCustomRoutes(project, routesFile);

  const createFields = extractSchemaFields(
    schemasFile,
    `create${modelName}Schema`,
  );
  const updateFields = extractSchemaFields(
    schemasFile,
    `update${modelName}Schema`,
  );
  const updateHasRefine = schemaHasRefine(
    schemasFile,
    `update${modelName}Schema`,
  );

  const baseIsProtected = isBaseRouterProtected(project, routesFile);
  const baseAuth = baseIsProtected ? { type: "JWT" } : null;

  const customGetAll = customRoutes.find(
    (r) => r.method === "GET" && (r.path === "/" || r.path === ""),
  );

  // GET /
  endpoints.push({
    method: "GET",
    path: basePath,
    auth: customGetAll
      ? customGetAll.isProtected
        ? { type: "JWT", role: customGetAll.requiredRole }
        : null
      : baseAuth,
    requestQuery: {
      pagination: { page: "number, default 1", pageSize: "number, default 20" },
      sort: "optional array of { field, direction }",
      filters: "optional array of { field, operator, value }",
      search: "optional string",
    },
    response: { status: 200, shape: `${modelName}[]` },
  });

  // GET /:id
  endpoints.push({
    method: "GET",
    path: `${basePath}/:id`,
    auth: baseAuth,
    requestParams: { id: "string (uuid)" },
    response: { status: 200, shape: modelName },
  });

  // POST /
  endpoints.push({
    method: "POST",
    path: basePath,
    auth: baseAuth,
    requestBody: schemaKeys.has("create")
      ? toBodyFieldMap(createFields)
      : undefined,
    response: { status: 201, shape: modelName },
  });

  // PUT /:id
  endpoints.push({
    method: "PUT",
    path: `${basePath}/:id`,
    auth: baseAuth,
    requestParams: { id: "string (uuid)" },
    requestBody: schemaKeys.has("update")
      ? toBodyFieldMap(updateFields)
      : undefined,
    responseNote: updateHasRefine
      ? "at least one field required (refine)"
      : undefined,
    response: { status: 200, shape: modelName },
  });

  // DELETE /:id
  endpoints.push({
    method: "DELETE",
    path: `${basePath}/:id`,
    auth: baseAuth,
    requestParams: { id: "string (uuid)" },
    response: { status: 204 },
  });

  // DELETE / (deleteAll) — check custom routes for protection info, fall back to unprotected
  const deleteAllCustom = customRoutes.find(
    (r) => r.method === "DELETE" && r.path === "/",
  );
  endpoints.push({
    method: "DELETE",
    path: basePath,
    auth: deleteAllCustom?.isProtected
      ? { type: "JWT", role: deleteAllCustom.requiredRole }
      : null,
    response: { status: 204 },
  });

  // Other custom routes (e.g. /summary), excluding the deleteAll and getAll we already handled
  for (const cr of customRoutes) {
    if (cr.method === "DELETE" && (cr.path === "/" || cr.path === "")) continue;
    if (cr.method === "GET" && (cr.path === "/" || cr.path === "")) continue;

    const fullPath = `${basePath}${cr.path}`;
    let responseShape = "unknown";
    const h = cr.handlerName.toLowerCase();
    if (h.includes("summary")) responseShape = "{ total: number }";
    else if (h.includes("getall") || h.includes("list"))
      responseShape = `${modelName}[]`;
    else if (h.includes("get") || h.includes("find") || h.includes("fetch"))
      responseShape = modelName;

    endpoints.push({
      method: cr.method,
      path: fullPath,
      auth: cr.isProtected ? { type: "JWT", role: cr.requiredRole } : null,
      response: { status: 200, shape: responseShape },
    });
  }

  return {
    moduleName,
    modelName,
    basePath,
    fields,
    relations,
    queryConfig,
    endpoints,
  };
}

function mapPrismaScalarToTs(prismaType: string): string {
  switch (prismaType) {
    case "String":
      return "string";
    case "Boolean":
      return "boolean";
    case "Int":
    case "Float":
    case "Decimal":
      return "number";
    case "DateTime":
      return "Date";
    case "Json":
      return "any";
    case "Bytes":
      return "Buffer";
    default:
      return prismaType; // relation type name
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const provider = new PrismaSchemaProvider(PRISMA_SCHEMA_PATH);
  const allModels = await provider.getModels();

  const project = new Project({ skipAddingFilesFromTsConfig: true });

  if (!fs.existsSync(MANIFESTS_DIR)) {
    fs.mkdirSync(MANIFESTS_DIR, { recursive: true });
  }

  const moduleNames = subdirs(MODULES_DIR);
  const indexEntries: Array<{
    moduleName: string;
    modelName: string;
    basePath: string;
    manifestFile: string;
  }> = [];

  for (const moduleName of moduleNames) {
    if (moduleName === "health") {
      console.log(`Skipping health module (no domain model)`);
      continue;
    }

    const modelName = capitalize(moduleName);
    const model = allModels.find((m) => m.name === modelName);

    if (!model) {
      console.log(
        `Skipping ${moduleName} — no matching Prisma model '${modelName}' found`,
      );
      continue;
    }

    console.log(`Generating manifest for module: ${moduleName}`);
    const manifest = buildManifest(moduleName, model, allModels, project);

    const outFile = path.join(MANIFESTS_DIR, `${moduleName}.manifest.json`);
    fs.writeFileSync(outFile, JSON.stringify(manifest, null, 2), "utf8");
    console.log(`  ✓ Written → ${outFile}`);

    indexEntries.push({
      moduleName,
      modelName,
      basePath: manifest.basePath,
      manifestFile: `${moduleName}.manifest.json`,
    });
  }

  const indexFile = path.join(MANIFESTS_DIR, "_index.manifest.json");
  fs.writeFileSync(
    indexFile,
    JSON.stringify({ modules: indexEntries }, null, 2),
    "utf8",
  );
  console.log(`\n✓ Index written → ${indexFile}`);
  console.log(`Modules: ${indexEntries.map((e) => e.moduleName).join(", ")}`);
}

main().catch((err) => {
  console.error("generate-manifest failed:", err);
  process.exit(1);
});
