import { Manifest, Field } from '../../../generate-modules';

export function generateFormTemplate(manifest: Manifest): string {
  const { moduleName, modelName, fields } = manifest;
  
  // Exclude auto-generated fields (id, createdAt, updatedAt) and relations for the basic form.
  // In a real app we might handle relations with select inputs.
  const formFields = fields.filter((f: Field) => !f.autoGenerated && !f.isRelation);

  const fieldsConfig = formFields.map((f: Field) => {
    let type = "text";
    if (f.tsType === 'number') type = 'number';
    if (f.tsType === 'Date') type = 'date';
    // Add boolean as checkbox if DynamicForm supported it, else stick to text/number
    
    return `{
      name: "${f.name}",
      label: "${f.name.charAt(0).toUpperCase() + f.name.slice(1)}",
      type: "${type}",
      placeholder: "Enter ${f.name}",
    }`;
  }).join(',\n    ');

  return `
"use client";

import React, { useTransition } from "react";
import { useRouter } from "next/navigation";
import { DynamicForm, FieldConfig } from "@/components/shared/DynamicForm";
import { create${modelName}Schema, update${modelName}Schema, Create${modelName}SchemaType, Update${modelName}SchemaType } from "../types/${moduleName}.zod";
import { create${modelName}Action, update${modelName}Action } from "../actions/${moduleName}.actions";
import { ${modelName} } from "../types/${moduleName}.types";

interface ${modelName}FormProps {
  initialData?: ${modelName};
}

export function ${modelName}Form({ initialData }: ${modelName}FormProps) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();

  const isEditing = !!initialData;

  const fields: FieldConfig<any>[] = [
    ${fieldsConfig}
  ];

  const onSubmit = async (values: any) => {
    startTransition(async () => {
      try {
        if (isEditing && initialData?.id) {
          await update${modelName}Action(initialData.id, values);
        } else {
          await create${modelName}Action(values);
        }
        router.push("/${moduleName}");
        router.refresh();
      } catch (error) {
        console.error("Form submission error", error);
        // Handle error state (e.g. toast)
      }
    });
  };

  return (
    <div className="max-w-2xl mx-auto p-6 bg-white rounded-lg shadow">
      <h2 className="text-2xl font-bold mb-6">{isEditing ? "Edit" : "Create"} ${modelName}</h2>
      <DynamicForm
        schema={isEditing ? update${modelName}Schema : create${modelName}Schema}
        fields={fields}
        defaultValues={initialData || {}}
        onSubmit={onSubmit}
        submitLabel={isEditing ? "Save Changes" : "Create"}
        isPending={isPending}
      />
    </div>
  );
}
`.trim();
}
