import { Manifest, Field } from '../../../generate-modules';

export function generateTypesTemplate(manifest: Manifest): string {
  const { modelName, fields, relations } = manifest;

  const relationImports = (relations || []).map((rel: any) => {
    if (rel.relatedModule && rel.relatedModule !== manifest.moduleName) {
      return `import { ${rel.relatedModel} } from '../../${rel.relatedModule}/types/${rel.relatedModule}.types';`;
    }
    return '';
  }).filter(Boolean).join('\n');

  const interfaces = `
${relationImports}

export interface ${modelName} {
${fields.map((f: Field) => `  ${f.name}${f.optional ? '?' : ''}: ${f.tsType};`).join('\n')}
}

// Omit auto-generated fields for creation
export type Create${modelName}Input = Omit<${modelName}, ${fields.filter((f: Field) => f.autoGenerated).map((f: Field) => `'${f.name}'`).join(' | ')}>;

export type Update${modelName}Input = Partial<Create${modelName}Input>;
`;

  return interfaces.trim();
}
