import { Manifest, Field } from '../../../../generate-modules';

function getDefaultValueForType(tsType: string): string {
  if (tsType === 'string') return "'test-string'";
  if (tsType === 'number') return "1";
  if (tsType === 'boolean') return "true";
  if (tsType === 'Date') return "new Date()";
  if (tsType.endsWith('[]')) return "[]";
  return "{} as any";
}

export function generateFactoryTemplate(manifest: Manifest): string {
  const { moduleName, modelName, fields } = manifest;

  const createFields = fields.filter((f: Field) => !f.autoGenerated);
  
  const createOverrides = createFields.map((f: Field) => {
    return `    ${f.name}: ${getDefaultValueForType(f.tsType)},`;
  }).join('\n');

  const modelOverrides = fields.map((f: Field) => {
    return `    ${f.name}: ${getDefaultValueForType(f.tsType)},`;
  }).join('\n');

  return `
import { ${modelName}, Create${modelName}Input } from '../../types/${moduleName}.types';

export function buildCreate${modelName}Input(overrides?: Partial<Create${modelName}Input>): Create${modelName}Input {
  return {
${createOverrides}
    ...overrides,
  };
}

export function build${modelName}(overrides?: Partial<${modelName}>): ${modelName} {
  return {
${modelOverrides}
    ...overrides,
  };
}
`.trim();
}
